[project]
name = "mini-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataclasses>=0.8",
    "torch>=2.8.0",
    "transformers>=4.57.0",
    "typing>=3.10.0.0",
]
